# Generated by Django 3.1.1 on 2020-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
