# Generated by Django 3.1.1 on 2020-10-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_posts_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='up_votes',
        ),
    ]
